version: '2'
services:
  #
  # [ server stack ]
  #
  # - postgrest
  # - postgres/postgis + pg_chichinabo
  #
  api:
    restart: always
    # comment on build if want to use the dockerhub build
    build:
      context: .
      dockerfile: Dockerfile-api
    image: chichinabo/popyramids_api
    container_name: popyramids_api
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      POSTGREST_DBHOST: db
      POSTGREST_DBNAME: popyramids_db
      POSTGREST_DBPORT: 5432
      POSTGREST_DBUSER: chichinabo
      POSTGREST_DBPASS: chichinabo
      POSTGREST_DBPOOL: 200
      POSTGREST_PORT: 3000
      POSTGREST_SCHEMA: dms
      POSTGREST_ANOUSER: apis
      POSTGREST_JWT_SECRET: notasecret
      POSTGREST_MAX_ROWS: 1000000
    networks:
      - backend

  db:
    restart: always
    # comment on build if want to use the dockerhub build
    build:
      context: .
      dockerfile: Dockerfile-db
    image: chichinabo/popyramids_db
    container_name: popyramids_db
    ports:
      - "5433:5432"
    # named volumes come here into play
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    environment:
      POSTGRES_PASSWORD: chichinabo
      POSTGRES_USER: chichinabo
    networks:
      - backend

#
# [ volumes definition ]
#
# creates Docker volumes which can be mounted by other containers too e.g. for backup
#
volumes:
  postgres_data:
    driver: local
  postgres_backups:
    driver: local

#
# [ networks definition ]
#
networks:  
#  frontend:
#    driver: bridge
  backend:
    driver: bridge
